PutAVettoWork.Site/Models/EventPost.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PutAVettoWork.Site.Models
{
    public class EventPost
    {
        public int Id { get; set; }

        [Required, MinLength(2, ErrorMessage = "Minimum of 2 characters")]
        public string Name { get; set; }

        public string Slug { get; set; }

        [Required, MinLength(2, ErrorMessage = "Minimum of 2 characters")]
        public string Desciption { get; set; }

        [Required, MinLength(2, ErrorMessage = "Minimum of 2 characters")]
        public string Content { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Please choose a category!")]
        [Display(Name = "Category")]
        public int CategoryId { get; set; }

        [ForeignKey("CategoryId")]
        public virtual Category Category { get; set; }
    }
}

PutAVettoWork.Site/Controllers/EventPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PutAVettoWork.Site.Data;
using PutAVettoWork.Site.Models;

namespace PutAVettoWork.Site.Controllers
{
    public class EventPostsController : Controller
    {

        private readonly GenDynContext context;

        public EventPostsController(GenDynContext context)
        {
            this.context = context;
        }

        //GET /events
        public async Task<IActionResult> Index()
        {

            return View(await context.EventPosts.OrderByDescending(x => x.Id).ToListAsync());
        }

        // GET /eventposts/id
        public async Task<IActionResult> Eventpost(int id)
        {
            EventPost eventPost = await context.EventPosts.Include(x => x.Category).FirstOrDefaultAsync(x => x.Id == id);
            if (eventPost == null)
            {
                return NotFound();
            }

            return View(eventPost);
        }
    }
}

PutAVettoWork.Site/Views/EventPosts/Eventpost.cshtml
@model PutAVettoWork.Site.Models.EventPost

@{
    ViewData["Title"] = "Eventpost";
}

<div>
    <h3>@Model.Name</h3>
    <hr />
    <div class="mt-3 mb-2">
        @Html.Raw(Model.Content)
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PutAVettoWork.Site/Views/EventPosts/Index.cshtml
@model IEnumerable<EventPost>

@{
    ViewData["Title"] = "Events";
}

<div style="padding-top: 20px; padding-left: 10px; padding-bottom: 25px;">
    <h1>Upcoming Events</h1>
    <p>Check out all of the events coming soon! If there are none, check back again soon!</p>

</div>

<div class="row">
    @foreach(var item in Model)
    {

    <div class="col-10" id="cardlist">
        <div id="eventcard">
            <h3>@item.Name</h3>
            @Html.Raw(item.Desciption)

            <a asp-controller="EventPosts" asp-action="Eventpost" asp-route-id="@item.Id" class="btn btn-outline-info">Read More</a>
        </div>
    </div>

    }


</div>