PutAVettoWork.Site/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PutAVettoWork.Site.Data;
using PutAVettoWork.Site.Models;

namespace PutAVettoWork.Site.Controllers
{
    public class PagesController : Controller
    {
        private readonly GenDynContext context;

        public PagesController(GenDynContext context)
        {
            this.context = context;
        }

        // GET / or /slug
        public async Task<IActionResult> Page(string slug)
        {
            if (slug == null)
            {
                return View(await context.Pages.Where(x => x.Slug == "home").FirstOrDefaultAsync());
            }

            Page page = await context.Pages.Where(x => x.Slug == slug).FirstOrDefaultAsync();

            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }
    }
}

PutAVettoWork.Site/Data/MainViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PutAVettoWork.Site.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PutAVettoWork.Site.Data
{
    public class MainViewComponent : ViewComponent
    { 
        private readonly GenDynContext context;

    public MainViewComponent(GenDynContext context)
    {
        this.context = context;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var pages = await GetPagesAsync();
        return View(pages);
    }

    private Task<List<Page>> GetPagesAsync()
    {
        return context.Pages.OrderBy(x => x.Sorting).ToListAsync();
    }
}
}

PutAVettoWork.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Put Veterans To Work</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <nav class="navbar navbar-dark sticky-top navbar-expand-lg fixed-top">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Put Veterans To Work</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav flex-grow-1">
                    @await Component.InvokeAsync("Main")
                </ul>
                <ul class="nav navbar-nav ml-auto">
                    @if (User?.Identity?.IsAuthenticated ?? false)
                    {
                        <li class="nav-item">
                            <a asp-controller="Account" asp-action="Edit" class="btn btn-primary">My Account</a>
                        </li>
                        <li class="nav-item ml-1">
                            <a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Hi, @User.Identity.Name, Log out</a>
                        </li>
                        @if (User.IsInRole("admin") || User.IsInRole("editor"))
                        {
                            <li class="nav-item ml-1">
                                <a asp-area="Admin" asp-controller="Pages" asp-action="Index" class="btn btn-success">Admin Area</a>
                            </li>
                        }
                    }
                    else
                    {
                        <li class="nav-item navright">
                            <a asp-controller="Account" asp-action="Login" class="nav-link text-dark">Log in</a>
                        </li>
                        @*<li class="nav-item ml-1 navright">
                                <a asp-controller="Account" asp-action="Register" class="btn btn-primary">Register</a>
                            </li>*@
                    }
                </ul>
            </div>
        </div>
    </nav>
    <!-- HEADER -->
    <section id="header" class="jumbotron text-center mb-5" style="height: 300px; text-align:left">
        <h1 style="color: white; font-weight: 400;" class="display-2">Put Veterans To Work</h1>
        <h3 style="color: white; font-weight: 400" class="">We Are Here for Those Who WERE There for Us!</h3>
    </section>
    <!-- END HEADER -->


    <div class="container">
        <partial name="_NotificationPartial" />
        @RenderBody()
    </div>

    @if (!User.IsInRole("admin") || !User.IsInRole("editor"))
    {
        <!-- STAY CONNECTED -->
        <div class="container my-5">
            <div id="stayconnected" class="text-center">
                <hr class="my-5">
                <h3>Stay Connected</h3>
                <div class="d-flex justify-content-around pt-4">
                    <a class="btn btn-lg btn-outline-dark" href="https://www.facebook.com/groups/putveteranstowork/"><i class="fab fa-facebook-square"></i> Join our Facebook Page!</a>
                    <a class="btn btn-lg btn-outline-dark" href="https://www.linkedin.com/groups/8615484/"><i class="fab fa-linkedin"></i> Find us on Linkedin!</a>
                    <a class="btn btn-lg btn-outline-dark" href="https://twitter.com/PutAVetToWork"><i class="fab fa-twitter"></i> Follow us on Twitter!</a>
                </div>
            </div>
        </div>
        <hr class="mt-5">
        <!-- STAY CONNTECTED END -->
    }



    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Put Veterans To Work
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PutAVettoWork.Site/Views/Shared/_SecondaryLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Put Veterans To Work</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <nav class="navbar sticky-top navbar-expand-lg fixed-top">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Put Veterans To Work</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav flex-grow-1">
                    @await Component.InvokeAsync("Main")
                </ul>
                <ul class="nav navbar-nav ml-auto">
                    @if (User?.Identity?.IsAuthenticated ?? false)
                    {
                        <li class="nav-item">
                            <a asp-controller="Account" asp-action="Edit" class="btn btn-primary">My Account</a>
                        </li>
                        <li class="nav-item ml-1">
                            <a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Hi, @User.Identity.Name, Log out</a>
                        </li>
                        @if (User.IsInRole("admin") || User.IsInRole("editor"))
                        {
                            <li class="nav-item ml-1">
                                <a asp-area="Admin" asp-controller="Pages" asp-action="Index" class="btn btn-success">Admin Area</a>
                            </li>
                        }
                    }
                    else
                    {
                        <li class="nav-item navright">
                            <a asp-controller="Account" asp-action="Login" class="nav-link text-dark">Log in</a>
                        </li>
                        @*<li class="nav-item ml-1 navright">
                                <a asp-controller="Account" asp-action="Register" class="btn btn-primary">Register</a>
                            </li>*@
                    }
                </ul>
            </div>
        </div>
    </nav>


    <div class="container">
        <partial name="_NotificationPartial" />
        @RenderBody()
    </div>



    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Put Veterans To Work
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>